name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests (optional)
        run: npm test
        continue-on-error: true  # Remove this if you want to fail on test errors

      - name: Build project
        run: npm run build

      # - name: Deploy (optional)
      #   run: echo "Add your deploy command here"
